services:
  sut:
    build: ./MyDotNetApp
    environment:
      - ASPNETCORE_URLS=http://+:8080

  tests:
    build: ./MyTestProject
    depends_on:
      - sut
    environment:
      - TEST_BASE_URL=http://sut:8080