services:
  sut:
    build: ./MyDotNetApp
    environment:
      - ASPNETCORE_URLS=http://+:8080

  tests:
    image: mcr.microsoft.com/playwright/dotnet:v1.59.0-jammy
    depends_on:
      - sut
    environment:
      - TEST_BASE_URL=http://sut:8080
    # Map the entire repository root so paths match exactly
    volumes:
      - .:/src
    # Set the working directory to the specific folder containing the .csproj
    working_dir: /src/MyTestProject
    # Run the test
    command: /bin/bash -c "dotnet test"